### PR TITLE
docker integration

### PR DESCRIPTION
**Pull request by wolflu05**
This PR adds a simple docker file to run this awesome cache proxy via docker to don't blow up the system with python dependencies. It would be great if you can provide some pre-build images for easier usage, so that the build process is not needed.

### CODE REVIEW

**Comment by RobinvandenHurk** [comment]
Thanks for your contribution! I'll look into this hopefully within the next few days. Meanwhile, I created issue #2 to track progress for pre-built docker images :)

**Comment by wolflu05** [comment]
Hello, any updates on this?

**Comment by RobinvandenHurk** [comment]
Hi @wolflu05! So sorry for the wait. Been busy with other work and, to be honest, this one completely left my mind. Looking into it now. Hope to get back to you soon!

**Comment by RobinvandenHurk** [comment]
Hi @wolflu05! I have now created a prebuilt @ [DockerHub](https://hub.docker.com/repository/docker/robinvandenhurk/cache-proxy). Also updated the Readme.md so the whole thing is a bit easier to understand. Everything seems to be working fine. Would you mind reading through the readme and giving it a go?

**Comment by wolflu05** [comment]
Looks good. Good idea to fix the empty cache file issue via enhancing the code and not creating it via echo 😀

**Comment by wolflu05** [comment]
Seems like I cannot access the image. If I try to load the docker hub page I have to sign in.

**Comment by RobinvandenHurk** [comment]
@wolflu05 Seems like I there's a admin view and a public view. I gave you the admin one, which is why you couldn't access it. Silly me! Try [this link](https://hub.docker.com/r/robinvandenhurk/cache-proxy) instead :)

**Comment by wolflu05** [comment]
Youre right. Works now. Looks good to me.

**Comment by RobinvandenHurk** [comment]
Thanks again for your contribution @wolflu05! Merged!

**Pull request merged**
